import type { Metadata } from "next";
import PublicPolicyPage from "@/components/public/PublicPolicyPage";

export const metadata: Metadata = {
  title: "Online Shipment Booking Terms | Swiftline Cargo",
  description:
    "Terms for booking and paying for a Swiftline international shipment online.",
  alternates: { canonical: "/terms-and-conditions" },
};
export default function TermsPage() {
  return (
    <PublicPolicyPage
      eyebrow="Swiftline online booking"
      title="Terms and conditions"
      summary="These terms apply when a person or company books a shipment through Swiftline's public online booking service."
    >
      <h2>1. Information you provide</h2>
      <p>
        You must provide complete and accurate sender, receiver, parcel, value,
        customs and identity information. If you provide information about
        another person, you confirm that you are authorised to do so and have
        given them any required privacy notice.
      </p>
      <h2>2. Quotes and payment</h2>
      <p>
        The final online quote is calculated by our server from the approved
        Band C rate card and configured route charges. It is valid for 30
        minutes and for the shipment details shown. Changing a parcel, route or
        document invalidates that quote. Payment is collected in Indian rupees
        through Razorpay.
      </p>
      <h2>3. Acceptance and verification</h2>
      <p>
        Payment confirmation creates a Swiftline booking and AWB. A booking
        remains subject to document, customs, security, weight, dimension and
        contents verification. Swiftline may hold or refuse goods that are
        unlawful, unsafe, incorrectly declared or outside the selected service.
      </p>
      <h2>4. Labels and handover</h2>
      <p>
        You must print and securely attach the Swiftline label supplied for each
        parcel and package goods appropriately for international transport. A
        downstream carrier label, where needed, is generated by authorised
        Swiftline staff and is not shown in the public checkout.
      </p>
      <h2>5. Charges after inspection</h2>
      <p>
        The online price is based on the measurements and declarations you
        provide. If staff verification finds a material difference, Swiftline
        will contact you before any additional amount is collected or
        operational change is made. This release does not include insurance or
        pickup.
      </p>
      <h2>6. Customer changes</h2>
      <p>
        Public customers cannot amend, cancel or rebook online. Contact
        Swiftline for help. Any staff action is recorded and handled under the
        cancellation and refund policy.
      </p>
      <h2>7. Liability and law</h2>
      <p>
        Liability, customs responsibility, delivery estimates and service
        exclusions are governed by applicable law and any service-specific
        carriage terms provided by Swiftline. Nothing in these terms excludes a
        right or liability that cannot lawfully be excluded.
      </p>
      <h2>8. Contact</h2>
      <p>
        Questions and booking help:{" "}
        <a href="mailto:Info@swiftlinefreight.com">Info@swiftlinefreight.com</a>{" "}
        or +91 70271 16600.
      </p>
    </PublicPolicyPage>
  );
}
